apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-app
  labels:
    app: docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-app
  template:
    metadata:
      labels:
        app: docker-app
    spec:
      containers:
        - name: docker-app
          image: yhy1045/docker-app:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: HELLO_CONFIG
              value: "Hello Config!!"
            - name: SPRING_PROFILE
              value: "production"
            - name: ACTIVE_MQ_HOST
              value: "activeMq"
            - name: TZ
              value: "Asia/Seoul"
          volumeMounts:
            - name: log-volume
              mountPath: /log/docker-app
      volumes:
        - name: log-volume
          hostPath:
            path: /Users/patrickyoo/data/logs/docker-app
      restartPolicy: Always
