
spring:
  datasource-primary:
    url: jdbc:mysql://localhost:3306/patrick-lab?useUnicode=true&serverTimezone=Asia/Seoul
    username: patrick-lab
    password: patrick-lab
    driverClassName: com.mysql.cj.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hbm2ddl:
        auto: none
  datasource-secondary:
    url: jdbc:mysql://localhost:3306/patricklab-second?useUnicode=true&serverTimezone=Asia/Seoul
    username: patricklab-second
    password: patricklab-second
    driverClassName: com.mysql.cj.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hbm2ddl:
        auto: none

  redis:
    host: 127.0.0.1
    port: 6379


  jpa:
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        query:
          in_clause_parameter_padding: true
    open-in-view: false
server:
  port: 9991
