
spring:
  datasource-primary:
    url: jdbc:mysql://localhost:3306/patricklab?useUnicode=true&serverTimezone=Asia/Seoul
    username: patricklab
    password: patricklab
    driverClassName: com.mysql.cj.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hbm2ddl:
        auto: none
  datasource-secondary:
    url: jdbc:mysql://localhost:3306/patricklab-second?useUnicode=true&serverTimezone=Asia/Seoul
    username: patricklab-second
    password: patricklab-second
    driverClassName: com.mysql.cj.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hbm2ddl:
        auto: none
  datasource-tertiary:
    url: jdbc:mysql://10.147.1.90:23306/cmc_api?characterEncoding=UTF-8
    username: imc-dev
    password: humuson0722
    driverClassName: com.mysql.cj.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hbm2ddl:
        auto: none

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        query:
          in_clause_parameter_padding: true
    open-in-view: false
server:
  port: 9991
