server:
  port: 9999
  tomcat:
    threads:
      max: 1 # 스레드 최대 수
      min-spare: 1 # 활성화 상태로 유지할 최소 쓰레드의 개수


docker:
  config:
    test: ${HELLO_CONFIG:Hello Docker!!}

spring:
  activemq:
    broker-url: tcp://${ACTIVE_MQ_HOST:localhost}:61616?jms.useAsyncSend=true&wireFormat.tightEncodingEnabled=false
    user: admin
    password: admin

