

server:
  port: 9994

spring:

  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:testdb;MODE=MySQL'
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        query:
          fail_on_pagination_over_collection_fetch: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

